export const SET_LOADING = 'SET_LOADING';
export const SET_COINS_LIST = 'SET_COINS_LIST';
export const SET_COINS_TABLE_DATA = 'SET_COINS_TABLE_DATA';
export const SET_COINS_NUMBER = 'SET_COINS_NUMBER';
export const SET_RESULTS_PER_PAGE = 'SET_RESULT_PER_PAGE';
export const SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE';
export const SET_VC_CURRENCY = 'SET_VC_CURRENCY';
export const SET_ORDER_BY = 'SET_ORDER_BY';
